# docker run -v `pwd`/content/:/data/content/ -v `pwd`/config/config.default.js:/opt/raneto/example/config.default.js -p 3000:3000 -d appsecco/raneto
#
# Reference (https://github.com/sparkfabrik/docker-node-raneto)
# Using official node:slim from the dockerhub (https://hub.docker.com/_/node/)
ARG IMAGE_REPOSITORY
# pull official base image
# FROM ${IMAGE_REPOSITORY}/node:slim
FROM ${IMAGE_REPOSITORY}/node:13.12.0-alpine
# MAINTAINER Madhu Akula <madhu@appsecco.com>

# See https://stackoverflow.com/questions/29261811/use-docker-compose-env-variable-in-dockerbuild-file
ARG PROXY_USER
ARG PROXY_PASSWORD
ARG PROXY_FQDN
ARG PROXY_PORT

ENV HTTP_PROXY="http://${PROXY_USER}:${PROXY_PASSWORD}@${PROXY_FQDN}:${PROXY_PORT}"
ENV HTTPS_PROXY="http://${PROXY_USER}:${PROXY_PASSWORD}@${PROXY_FQDN}:${PROXY_PORT}"

# Change the raneto version based on version you want to use
ENV RANETO_VERSION 0.16.4
ENV RANETO_INSTALL_DIR /opt/raneto

# Install missing curl from node:alpine image

RUN apk --no-cache add curl

# Get Raneto from sources
RUN cd /tmp \
    && curl -SLO "https://github.com/gilbitron/Raneto/archive/$RANETO_VERSION.tar.gz" \
    && mkdir -p $RANETO_INSTALL_DIR \
    && tar -xzf "$RANETO_VERSION.tar.gz" -C $RANETO_INSTALL_DIR --strip-components=1 \
    && rm "$RANETO_VERSION.tar.gz"

# Installing dependencies
RUN npm install --global gulp-cli pm2 path

# Entering into the Raneto directory
WORKDIR $RANETO_INSTALL_DIR

# Copy all
COPY . $RANETO_INSTALL_DIR

# Add our own implementation of multiple-instances.js
ADD example $RANETO_INSTALL_DIR/example

# Installing Raneto
RUN npm install \
    && rm -f $RANETO_INSTALL_DIR/example/config.custom.js \
    && gulp

# Exposed the raneto default port 3000
EXPOSE 3000

# Starting the raneto, referencing our own "custom' directory"
CMD [ "pm2", "start", "/opt/raneto/example/multiple-instances.js", "--name", "raneto", "--no-daemon" ]
